[package]
name="cppl"
version="0.1.0"
edition="2021"
license="MIT OR Apache-2.0"


[features]
recreate_source=[]


[dependencies]
logos="0.12.1"
lalrpop-util="0.19.8"


[build-dependencies]
lalrpop="0.19.8"
