[package]
name="cppl_parser"
version="0.1.0"
edition="2021"
license="MIT OR Apache-2.0"


[dependencies]
cppl_error={path="../error"}
cppl_ast={path="../ast"}
cppl_lexer={path="../lexer"}
lalrpop-util="0.19.8"


[build-dependencies]
lalrpop="0.19.8"
